title       = "courtlistener"
baseURL     = "https://courtlistener-cli.tamnd.com/"
description = "A command line for courtlistener."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/courtlistener-cli"
